name: CI

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:

  merge_group:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Build
        run: bun run build

      - name: Publish to pkg.pr.new
        run: bun pkg-pr-new publish --packageManager=bun './packages/*' --comment=off

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Types
        run: bun check-types

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Lint
        run: bun lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Test
        run: bun run test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Start Surfpool
        run: |
          docker run -d --name surfpool -p 8899:8899 -p 8900:8900 surfpool/surfpool:main start --offline --no-tui
          bunx wait-on tcp:localhost:8899 --verbose --timeout 10000
          bunx wait-on tcp:localhost:8900 --verbose --timeout 10000

      - name: Test Integration
        run: bun run test:integration

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Spelling
        run: bun spell-check
