name: Install Dependencies
description: Sets up Bun, then installs all dependencies

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: lts/krypton

    - name: Install bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
      with:
        bun-version-file: '.bun-version'

    - name: Install dependencies
      shell: bash
      run: bun install

# TODO: This check can go when this issue is fixed https://github.com/oven-sh/bun/issues/24223
    - name: Check for dirty git repo
      shell: bash
      run:  git diff --quiet --ignore-submodules HEAD
